### ISSUE TITLE
it would be nice to have the option to set the precision

### ISSUE THREAD

**Issue by ktarplee** [stereosteve/si-tools#1]
Right now you use toFixed(5).  I think that value should be a argument to the format function.   In particular I want to have toFixed(2) called instead on the number.

**Comment by stereosteve** [comment]
You can call `SI.compute(x);` directly for more control, and it will return an object with `input`, `number`, and `prefix`.  You can then do `number.toFixed(2)`.  `prefix` will contain the SI letter that goes with the scaled number (i.e. `µ`).

Instead of adding an extra parameter to `format`, I think I'll update the readme to mention using `compute` for more control.

**Comment by ktarplee** [comment]
I am currently using compute().  It is more useful to have the option, hence the ticket.

**Comment by stereosteve** [comment]
Fair enough.  I added a `precision` parameter, see the tests for example usage.

**Comment by ktarplee** [comment]
Can you add a tag so this can be bower installed (you might want to use "npm version patch")?

**Comment by stereosteve** [comment]
Right... sorry forgot about that.  Tagged `1.1.1`

**Comment by ktarplee** [comment]
Thanks for making the tag for me.
